[
  {
    TraceId: Id_1,
    SpanId: Id_2,
    Name: internal,
    Resource: Quartz.Job.Execute,
    Service: Samples.Quartz,
    Type: custom,
    Tags: {
      env: integration_tests,
      fire.instance.id: <fire.instance.id>,
      job.group: group1,
      job.name: helloJob,
      job.type: QuartzSampleApp.HelloJob, Samples.Quartz,
      language: dotnet,
      otel.library.name: Quartz,
      otel.library.version: 4.0.0.0,
      otel.status_code: STATUS_CODE_UNSET,
      otel.trace_id: Guid_1,
      runtime-id: Guid_2,
      scheduler.id: NON_CLUSTERED,
      scheduler.name: DefaultQuartzScheduler,
      span.kind: internal,
      trigger.group: group1,
      trigger.name: helloTrigger,
      version: 1.0.0
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  },
  {
    TraceId: Id_3,
    SpanId: Id_4,
    Name: internal,
    Resource: Quartz.Job.Execute,
    Service: Samples.Quartz,
    Type: custom,
    Error: 1,
    Tags: {
      env: integration_tests,
      error.msg: Something went wrong,
      error.stack:
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
Quartz.JobExecutionException: Something went wrong
---> System.InvalidOperationException: Something went wrong
at QuartzSampleApp.ExceptionJob.Quartz.IJob.Execute(IJobExecutionContext context),
      error.type: Quartz.JobExecutionException,
      events: [{"name":"exception","time_unix_nano":<DateTimeOffset.Now>,"attributes":{"exception.message":"Something went wrong","exception.stacktrace":"Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False \n Quartz.JobExecutionException: Something went wrong\n ---> System.InvalidOperationException: Something went wrong\n   at QuartzSampleApp.ExceptionJob.Quartz.IJob.Execute(IJobExecutionContext context) in /Users/mohammad.islam/DDRepos/dd-trace-dotnet/tracer/test/test-applications/integrations/Samples.Quartz/Program.cs:line 100\n   --- End of inner exception stack trace ---\n   at QuartzSampleApp.ExceptionJob.Quartz.IJob.Execute(IJobExecutionContext context) in /Users/mohammad.islam/DDRepos/dd-trace-dotnet/tracer/test/test-applications/integrations/Samples.Quartz/Program.cs:line 105\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken) [See nested exception: System.InvalidOperationException: Something went wrong\n   at QuartzSampleApp.ExceptionJob.Quartz.IJob.Execute(IJobExecutionContext context) in /Users/mohammad.islam/DDRepos/dd-trace-dotnet/tracer/test/test-applications/integrations/Samples.Quartz/Program.cs:line 100]","exception.type":"Quartz.JobExecutionException"}}],
      fire.instance.id: <fire.instance.id>,
      job.group: group2,
      job.name: exceptionJob,
      job.type: QuartzSampleApp.ExceptionJob, Samples.Quartz,
      language: dotnet,
      otel.library.name: Quartz,
      otel.library.version: 4.0.0.0,
      otel.status_code: STATUS_CODE_ERROR,
      otel.trace_id: Guid_3,
      runtime-id: Guid_2,
      scheduler.id: NON_CLUSTERED,
      scheduler.name: DefaultQuartzScheduler,
      span.kind: internal,
      trigger.group: group2,
      trigger.name: exceptionTrigger,
      version: 1.0.0
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  }
]